const List aadesmulak = [
  {'image': "images/img/1.png", 'title': "रोक्न निषेध"},
  {'image': "images/img/2.png", 'title': "पर्किङ्ग निषेध"},
  {'image': "images/img/3.png", 'title': "प्रवेश निषेध"},
  {'image': "images/img/4.png", 'title': "दाहिने मोड्न निषेध"},
  {'image': "images/img/5.png", 'title': "बायाँ मोड्न निषेध"},
  {'image': "images/img/6.png", 'title': "यु टर्न गर्न निषेध"},
  {'image': "images/img/7.png", 'title': "अधिकतम गति"},
  {'image': "images/img/8.png", 'title': "सबारी चौडाही सिमा"},
  {'image': "images/img/9.png", 'title': "उछिन्न निषेध"},
  {'image': "images/img/10.png", 'title': "हर्न निषेध"},
  {'image': "images/img/11.png", 'title': "रोक हेर र जाऊ"},
  {'image': "images/img/12.png", 'title': "गति सिमा समाप्त"},
  {'image': "images/img/13.png", 'title': "सिधा मात्र जाउ"},
  {'image': "images/img/14.png", 'title': "आगाडी गएर बाया मोड"},
  {'image': "images/img/15.png", 'title': "कुनै तिर बाट जाउ"},
  {'image': "images/img/16.png", 'title': "सानो गोल घुम्ती"},
  {'image': "images/img/17.png", 'title': "सवारी भार सिमा"},
  {'image': "images/img/18.png", 'title': "बाया मोड"},
  {'image': "images/img/19.png", 'title': "बाया च्याप"},
  {'image': "images/img/20.png", 'title': "एक तर्फी सवारी"},
  {'image': "images/img/21.png", 'title': "रोक र जन्देउ"},
  {
    'image': "images/img/22.png",
    'title': "मूल सडक वा गोल घुम्ती मा आउने लाई पहिला जान देउ"
  },
  {'image': "images/img/23.png", 'title': "ट्रक निषेध"},
  {'image': "images/img/24.png", 'title': "सबारी लम्बाई सिमा"},
  {'image': "images/img/25.png", 'title': "सवारी उचाई सिमा"},
  {'image': "images/img/26.png", 'title': "एक्सल भार सिमा"},
  {'image': "images/img/27.png", 'title': "पैदल यात्री निषेध"},
  {'image': "images/img/28.png", 'title': "बेल गाडा निषेध"},
  {'image': "images/img/29.png", 'title': "गति सिमा समाप्त"},
  {'image': "images/img/30.png", 'title': "जाउ "},
];

const List chetanamulak = [
  {'image': "images/img/31.png", 'title': "टी जक्शन "},
  {'image': "images/img/32.png", 'title': "खतरा"},
  {'image': "images/img/33.png", 'title': "आगाडी दुइ तर्फी बाटो सिधा"},
  {'image': "images/img/34.png", 'title': "आगाडी दुइ तर्फी बाटो"},
  {'image': "images/img/35.png", 'title': "दाहिने मोड"},
  // {'image': "images/img/35.png", 'title': "दाहिने पुरा मोड"},
  {'image': "images/img/36.png", 'title': "दाहिने पुरा मोड"},
  {'image': "images/img/37.png", 'title': "साँघुरो पुल"},
  {'image': "images/img/38.png", 'title': "बढी उकालो"},
  {'image': "images/img/39.png", 'title': "खतरनाक दबेको बाटो"},
  {'image': "images/img/40.png", 'title': "दुवै तिर बाट साँघुरिएको सडक"},
  {'image': "images/img/41.png", 'title': "पहिरो झर्ने ठाउँ"},
  {'image': "images/img/42.png", 'title': "दाहिने तिरबाट साँघुरिएको बाटो"},
  {'image': "images/img/43.png", 'title': "दोहोरो मोड पहिले बायाँ"},
  {'image': "images/img/44.png", 'title': "वाई जंक्सन"},
  {'image': "images/img/45.png", 'title': "बायाँबाट सबारी आउन सक्छ"},
  {'image': "images/img/46.png", 'title': "दाहीनेबाट सबारी आउन सक्छ"},
  {'image': "images/img/47.png", 'title': "गोल घुम्ती"},
  {'image': "images/img/48.png", 'title': "आगाडी उचायी सिमा"},
  {'image': "images/img/49.png", 'title': "चौबाटो आगाडी सडक"},
  {'image': "images/img/50.png", 'title': "चौबाटो आगाडी साखा सडक"},
  {'image': "images/img/51.png", 'title': "बढी ओरालो"},
  {'image': "images/img/52.png", 'title': "पाल्तु जनावर"},
  {'image': "images/img/53.png", 'title': "कम उचाइमा डिलहरु"},
  {'image': "images/img/54.png", 'title': "उठेको बाटो"},
  {'image': "images/img/55.png", 'title': "पैदल यात्रीले बाटो काट्ने ठाउँ"},
  {'image': "images/img/56.png", 'title': "दाहिने साखा सडक"},
  {'image': "images/img/57.png", 'title': "एक पछि आर्को दोबाटोहरु"},
  {'image': "images/img/58.png", 'title': "दोहोरो बाटोहरु समाप्त"},
  {'image': "images/img/59.png", 'title': "ट्राफिक चिन्ह"},
  {'image': "images/img/60.png", 'title': "जंङ्गली जनावर"},
  {'image': "images/img/61.png", 'title': "अगाडी बाटोमा पैदल यात्री"},
  {'image': "images/img/62.png", 'title': "नदीको किनारा"},
  {'image': "images/img/63.png", 'title': "रेल गाढी गेट नभएको"},
  {'image': "images/img/64.png", 'title': "गिट्टी उछिट्टिटन सक्ने"},
  {'image': "images/img/65.png", 'title': "बाटोमा काम हुदै"},
  {'image': "images/img/66.png", 'title': "ज़ाच चौकी"},
  {'image': "images/img/67.png", 'title': "केटाकेटीहरु"},
  {'image': "images/img/68.png", 'title': "बायाँतिर तिखो मोड"},
  {'image': "images/img/69.png", 'title': "तिखो मोड (अस्थाई बाटो)"},
  {'image': "images/img/70.png", 'title': "टी जंक्शन (दायाँ बायाँ मोड )"}
];

const List jankarimulakchinha = [
  {'image': "images/img/71.png", 'title': "पार्किंग ईस्थल"},
  {'image': "images/img/72.png", 'title': "एक तर्फी बाटो"},
  {'image': "images/img/73.png", 'title': "वर्क शप"},
  {'image': "images/img/74.png", 'title': "प्राथिमिक उपचार सिबिर"},
  {'image': "images/img/75.png", 'title': "उछिने ठाउँ"},
  {'image': "images/img/76.png", 'title': "टेलिफोन"},
  {'image': "images/img/77.png", 'title': "बाटोको अन्त"},
  {'image': "images/img/78.png", 'title': "पैदल यात्री को बाटो"},
  {'image': "images/img/79.png", 'title': "पेट्रोल पम्प"},
  {'image': "images/img/80.png", 'title': "बस बस्ने ठाउँ"},
  {'image': "images/img/81.png", 'title': "अस्पताल"},
  {'image': "images/img/82.png", 'title': "जलपान ठाउँ"},
  {'image': "images/img/83.png", 'title': "पैदल यात्री र साइकल को बाटो"},
  {'image': "images/img/84.png", 'title': "रेस्टुरा"},
  {'image': "images/img/85.png", 'title': "पैदल यात्रीको बाटो"},
  {'image': "images/img/86.png", 'title': "साइकल को बाटो"},
  {'image': "images/img/87.png", 'title': "बस बिसौनी"},
  {'image': "images/img/88.png", 'title': "बन भोज क्षेत्र"},
  {'image': "images/img/89.png", 'title': "जेब्रा क्रस"},
  {'image': "images/img/90.png", 'title': "अत्यन्त जरुरि भए मात्र राख्न"},
  {'image': "images/img/91.png", 'title': "सडक छेउ का रेखाहरु"},
  {'image': "images/img/92.png", 'title': "सडक बीच का रेखाहरु"},
];